export default (res) => {
    res.json([
        {nome: 'América-MG', abreviacao: 'AME', id: 327, escudo: 'https://s.glbimg.com/es/sde/f/organizacoes/2018/01/24/AmericaMG-65.png'},
        {nome: 'Atlético-RN', abreviacao: 'ARN', id: 200, escudo: ''},
        {nome: 'Atlético-GO', abreviacao: 'AGO', id: 373, escudo: ''},
        {nome: 'Atlético-MG', abreviacao: 'CAM', id: 282, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2017/11/23/Atletico-Mineiro-escudo65px.png'},
        {nome: 'Avaí', abreviacao: 'AVA', id: 314, escudo: ''},
        {nome: 'Bahia', abreviacao: 'BAH', id: 265, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/bahia_60x60.png'},
        {nome: 'Botafogo', abreviacao: 'BOT', id: 263, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/botafogo_60x60.png'},
        {nome: 'Brasiliense', abreviacao: 'BRA', id: 203, escudo: ''},
        {nome: 'Ceara', abreviacao: 'CHA', id: 315, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2018/05/11/ceara-65x65.png'},
        {nome: 'Chapecoense', abreviacao: 'AME', id: 315, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2015/08/03/Escudo-Chape-165.png'},
        {nome: 'Náutico', abreviacao: 'NAU', id: 205, escudo: ''},
        {nome: 'Corinthians', abreviacao: 'COR', id: 264, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/corinthians_60x60.png'},
        {nome: 'Coritiba', abreviacao: 'COR', id: 294, escudo: ''},
        {nome: 'Criciuma', abreviacao: 'CRI', id: 206, escudo: ''},
        {nome: 'Cruzeiro', abreviacao: 'CRU', id: 283, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2015/04/29/cruzeiro_65.png'},
        {nome: 'CSA', abreviacao: 'CSA', id: 341, escudo: ''},
        {nome: 'Figueirense', abreviacao: 'FIG', id: 316, escudo: ''},
        {nome: 'Flamengo', abreviacao: 'FLA', id: 262, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2018/04/09/Flamengo-65.png'},
        {nome: 'Fluminense', abreviacao: 'FLU', id: 266, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2015/07/21/fluminense_60x60.png'},
        {nome: 'Fortaleza', abreviacao: 'FOR', id: 356, escudo: ''},
        {nome: 'Goiás', abreviacao: 'GOI', id: 290, escudo: ''},
        {nome: 'Grêmio', abreviacao: 'GRE', id: 284, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/gremio_60x60.png'},
        {nome: 'Guarani', abreviacao: 'GUA', id: 213, escudo: ''},
        {nome: 'Internacional', abreviacao: 'INT', id: 285, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2016/05/03/inter65.png'},
        {nome: 'Ipatinga', abreviacao: 'IPA', id: 214, escudo: ''},
        {nome: 'Joinville', abreviacao: 'JEC', id: 215, escudo: ''},
        {nome: 'Juventude', abreviacao: 'JUV', id: 216, escudo: ''},
        {nome: 'Paysandu', abreviacao: 'PAY', id: 218, escudo: ''},
        {nome: 'Palmeiras', abreviacao: 'PAL', id: 275, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/palmeiras_60x60.png'},
        {nome: 'Paraná', abreviacao: 'PAR', id: 217, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/13/parana_60x60.png'},
        {nome: 'Ponte Preta', abreviacao: 'PON', id: 303, escudo: ''},
        {nome: 'Paysandu', abreviacao: 'PAY', id: 218, escudo: ''},
        {nome: 'Portuguesa', abreviacao: 'POR', id: 219, escudo: ''},
        {nome: 'Santa Cruz', abreviacao: 'STC', id: 344, escudo: ''},
        {nome: 'Santo Andre', abreviacao: 'SAN', id: 220, escudo: ''},
        {nome: 'Santos', abreviacao: 'SAN', id: 277, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/santos_60x60.png'},
        {nome: 'São Caetano', abreviacao: 'SAO', id: 221, escudo: ''},
        {nome: 'São Paulo', abreviacao: 'SAO', id: 276, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/sao_paulo_60x60.png'},
        {nome: 'Sport', abreviacao: 'SPO', id: 292, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2015/07/21/sport65.png'},
        {nome: 'Vasco da Gama', abreviacao: 'VAS', id: 267, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2016/07/29/Vasco-65.png'},
        {nome: 'Vitória', abreviacao: 'VIT', id: 287, escudo: 'https://s.glbimg.com/es/sde/f/equipes/2014/04/14/vitoria_60x60.png'},
    ])
}


